name: 'Gorbet Design, Inc.'
favicon: null
layout_spectrum: 0.98241
typography_spectrum: 0.23433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#223e63'
    - '#7599b7'
    - '#bdbeba'
  brandStrength: 0.5
  lightness: 0.4986660049762577
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
